config/routes.rb
VocalBase::Application.routes.draw do
  get '/state_select' => 'countries_states#state_select'

  devise_for :users,
    path: '',
    path_names: {
      sign_out: 'logout'
    }

  resources :uploaded_files, only: [:new, :index, :show], path: 'arquivos',
    path_names: {
      :new => 'upload',
      :show => 'arquivo'
    }

  resources :audio_words, only: [:new, :create]
  resources :text_with_voices, only: [:new, :create]
  resources :texts, only: [:new, :create]

  root to: "static_pages#home"
end

app/models/audio_word.rb
class AudioWord < ActiveRecord::Base
  attr_accessible :country, :gender, :language, :sampling_freq, :state, :word

  has_one :uploaded_file, as: :owner_file

  # validates_presence_of :country, :gender, :language, :state, :word

  def file_path
  	unless uploaded_file.nil?
	  	uploaded_file.url
  	end
  end

  def title
  	word
  end
end

app/models/text.rb
class Text < ActiveRecord::Base
  attr_accessible :author, :category, :language, :title

  has_one :uploaded_file, as: :owner_file

  # validates_presence_of :author, :category, :language, :title

  def file_path
  	unless uploaded_file.nil?
	  	uploaded_file.url
  	end
  end

end

app/models/text_with_voice.rb
class TextWithVoice < ActiveRecord::Base
  attr_accessible :author, :category, :language, :title

  has_many :uploaded_files, as: :owner_file

  # validates_presence_of :author, :category, :language, :title

  def file_path
  	if voice_path.nil?
  		return text_path
  	else
  		return voice_path
  	end
  end

  def text_path
  	uploaded_files.each do |uf|
  		unless uf.format.in?["wma", "mp3", "ogg", "wav"]
  			return uf.url
  		end
  	end
  	return nil
  end

  def voice_path
  	uploaded_files.each do |uf|
  		if uf.format.in?["wma", "mp3", "ogg", "wav"]
  			return uf.url
  		end
  	end
  	return nil
  end
end

app/models/uploaded_file.rb
class UploadedFile < ActiveRecord::Base
  attr_accessible :url, :format

  belongs_to :user
  belongs_to :owner_file, polymorphic: true

  validates_presence_of :url

  before_save :set_format

  private

  	def set_format
  		if format.blank?
  			format = url.split(".").last
  		end
  	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, 
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
  				  :name, :gender, :country, :state, :city
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/audio_words_controller.rb
# -*- encoding : utf-8 -*-

class AudioWordsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create]
  
  def show
  end

  def new
    @audio_word = AudioWord.new
  end

  def create
    if params[:audio_word][:gender] == "Masculino"
      params[:audio_word][:gender] = true
    else
      params[:audio_word][:gender] = false
    end
    url = params[:audio_word].delete(:file_path)
    @audio_word = AudioWord.new params[:audio_word]
    if @audio_word.save
      @uploaded_file = UploadedFile.new
      @uploaded_file.owner_file = @audio_word
      @uploaded_file.user = current_user
      @uploaded_file.url = url
      @uploaded_file.format = params.delete(:format)
      if @uploaded_file.save
        flash[:success] = "Cadastro de palavra efetuado com sucesso."
        redirect_to root_path
      else
        @audio_word.destroy
        flash[:error] = "Por favor complete todos os campos obrigatórios corretamente."
        render :new
      end
    else
      flash[:error] = "Por favor complete todos os campos obrigatórios corretamente."
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/countries_states_controller.rb
class CountriesStatesController < ApplicationController
  def state_select
  	render partial: 'state_select'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/text_with_voices_controller.rb
# -*- encoding : utf-8 -*-

class TextWithVoicesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create]
  
  def show
  end

  def new
    @text_with_voice = TextWithVoice.new
  end

  def create
    text_url = params[:text_with_voice].delete(:text_path)
    voice_url = params[:text_with_voice].delete(:voice_path)

    @text_with_voice = TextWithVoice.new params[:text_with_voice]
    if @text_with_voice.save
      @text_file = @text_with_voice.uploaded_files.new
      @text_file.user = current_user
      @text_file.url = text_url
      @text_file.format = params.delete(:text_format)
      if @text_file.save
        @voice_file = @text_with_voice.uploaded_files.new
        @voice_file.user = current_user
        @voice_file.url = voice_url
        @voice_file.format = params.delete(:voice_format)
        if @voice_file.save
          flash[:success] = "Cadastro de texto com voz efetuado com sucesso."
          redirect_to root_path
        else
          @text_with_voice.destroy
          @text_file.destroy
          flash[:error] = "Por favor complete todos os campos obrigatórios corretamente."
          render :new
        end
      else
        @text_with_voice.destroy
        flash[:error] = "Por favor complete todos os campos obrigatórios corretamente."
        render :new
      end
    else
      flash[:error] = "Por favor complete todos os campos obrigatórios corretamente."
      render :new
    end
  end

  def edit
  end

  def update
  end
end

app/controllers/texts_controller.rb
# -*- encoding : utf-8 -*-

class TextsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create]
  
  def show
  end

  def new
    @text = Text.new
  end

  def create
    url = params[:text].delete(:text_path)
    @text = Text.new params[:text]
    if @text.save
      @text_file = UploadedFile.new
      @text_file.owner_file = @text
      @text_file.user = current_user
      @text_file.url = url
      @text_file.format = params.delete(:text_format)
      if @text_file.save
        flash[:success] = "Cadastro de texto efetuado com sucesso."
        redirect_to root_path
      else
        @text.destroy
        flash[:error] = "Por favor complete todos os campos obrigatórios corretamente."
        render :new
      end
    else
      flash[:error] = "Por favor complete todos os campos obrigatórios corretamente."
      render :new
    end
  end

  def edit
  end

  def update
  end
end

app/controllers/uploaded_files_controller.rb
class UploadedFilesController < ApplicationController
  def index
  	@all_words_raw = AudioWord.all
  	@all_words = search [:word, :language, :country, :state, :sampling_freq], @all_words_raw

  	@all_texts_raw = Text.all
  	@all_texts = search [:title, :author, :category, :language], @all_texts_raw

  	@all_texts_with_voices_raw = TextWithVoice.all
  	@all_texts_with_voices = search [:title, :author, :category, :language], @all_texts_with_voices_raw

  	if params[:Filtros] == "Palavra"
  		@all = @all_words
  	elsif params[:Filtros] == "Texto com Voz"
  		@all = @all_texts_with_voices
  	elsif params[:Filtros] == "Texto apenas"
  		@all = @all_texts
  	else
  		@all = (@all_words << @all_texts << @all_texts_with_voices).flatten
  	end
  end

  def show
    @me = UploadedFile.find params[:id]
  end
  
  def new
  	@uploaded_file = UploadedFile.new
  end

  private

  	def search attributes, raw
  		new_array = []
  		params[:search].split(" ").each do |word|
	  		attributes.each do |attr|
	  			new_raw = raw.dup
	  			new_raw.each do |rec|
	  				# if attr == :gender
	  				# 	if rec.gender == true && "masculino".include?(word.downcase)
							# @all_words << rec
			  		# 		@all_words_raw.delete(rec)
			  		# 		break
			  		# 	elsif rec.gender == false && "feminino".include?(word.downcase)
			  		# 		@all_words << rec
			  		# 		@all_words_raw.delete(rec)
			  		# 		break
	  				# 	end
	  				# end
	  				if !rec[attr].nil? && rec[attr].downcase.include?(word.downcase)
	  					new_array << rec
	  					raw.delete(rec)
	  				end
	  			end
	  		end
	  	end
	  	new_array
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/audio_words/create.html.haml
%h1 AudioWords#create
%p Find me in app/views/audio_words/create.html.haml

app/views/audio_words/edit.html.haml
%h1 AudioWords#edit
%p Find me in app/views/audio_words/edit.html.haml

app/views/audio_words/new.html.haml
.row-fluid
	.well.span8.offset2
		%h1 Cadastro de palavra:
		= simple_form_for @audio_word do |f|
			.span5.offset1
				%h3 Informações sobre a fala:
				= f.input :gender, label: "Gênero", collection: ["Masculino", "Feminino"], as: :radio_buttons, item_wrapper_class: 'inline'
				= hidden_field_tag :country_select_type, "audio_word"
				= render 'countries_states/country_select', f: f, type: :audio_word
				= f.input :language, label: "Idioma", collection: LANGUAGES
			.span5
				%h3 Informações Técnicas:
				= f.input :word, label: "Palavra:"
				= f.label :file_path, "Selecione um arquivo:"
				= f.filepicker_field :file_path, onchange: 'fileUploaded("format")', mimetypes: 'audio/*', class: "btn"
				= f.input :sampling_freq, label: "Frequência de amostragem:", placeholder: "opcional...", hint: "* Em Hertz"
				= hidden_field_tag :format
				= f.button :submit, "Cadastrar", class: "btn btn-primary"

= javascript_include_tag "filepicker_upload"

app/views/audio_words/show.html.haml
%h1 AudioWords#show
%p Find me in app/views/audio_words/show.html.haml

app/views/audio_words/update.html.haml
%h1 AudioWords#update
%p Find me in app/views/audio_words/update.html.haml

app/views/countries_states/_country_select.html.haml
= f.input :country, label: "País:", collection: COUNTRIES_STATES.keys.map {|x| x.to_s}, prompt: "-- Selecione seu país", input_html: {class: "country_select"}
= f.label :state, "Estado:"
= render partial: 'countries_states/state_select', locals: { parent_region: f.object.country ||= "", type: type }

= javascript_include_tag "country_state_select"

app/views/countries_states/_state_select.html.haml
.state_wrapper
	- parent_region ||= COUNTRIES_STATES[params[:parent_region].gsub("_", " ").to_sym]
	- type ||= params[:type].to_sym
	- selected = nil unless params[:type].nil?

	- if parent_region == ""
		%em Por favor selecione um país
	- elsif parent_region.length != 0
		- if selected.nil?
			= select type, :state, parent_region, prompt: "-- Selecione seu estado"
		- else
			= select type, :state, parent_region, selected: selected
	- else
		- if selected.nil?
			= text_field type, :state
		-else
			= text_field type, :state, selected

app/views/layouts/_header.html.haml
.navbar.navbar-fixed-top
	.navbar-inner
		.span12.offset1
			= link_to root_path, class: "brand" do
				= image_tag "logo.png"
				%p= "Vocal Base"
			%ul.nav
				%li= link_to "Upload", new_uploaded_file_path
				%li
					= form_tag uploaded_files_path, method: :get do
						%p
							= search_field_tag :search, params[:search], placeholder: "procurar..."
							= submit_tag "Procurar", name: nil, class: 'btn'
			.pull-right
				- if user_signed_in?
					%ul.nav
						%li
							%p= "Logged in as #{current_user.email}"
						%li= link_to "Sair", destroy_user_session_path, method: :delete
				- else
					.new_session
						= render 'users/sessions/new'
					= link_to_function "Não é cadastrado?", nil, id: "register", class: 'pull-right'
					#popover-register= render 'users/registrations/new'

:javascript
	$('#register').popover({
		title: "Cadastre-se",
		html: true,
		width: 300,
		content: function() {
			return $('#popover-register').html();
		},
		placement: 'bottom'
	});

app/views/layouts/application.html.haml
!!! 5
%html
	%head
		%title VocalBase
		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags
		= filepicker_js_include_tag
	%body
		= render 'layouts/header'
		.row-fluid
			- flash.each do |k, v|
				- k = :success if k == :notice
				.span8.offset2.alert{:class => "alert-#{k.to_s}"}
					%button.close{:type => "button", :'data-dismiss' => "alert"} &times;
					%p= v
		= yield

app/views/static_pages/home.html.haml
.hero-unit
	%h1 Seja bem vindo ao Vocal Base!
	%p Este é um projeto feito por Ariel Schvartz e Leonardo Gardel Valverde para a disciplina de Processamento de Voz

app/views/text_with_voices/create.html.haml
%h1 TextWithVoices#create
%p Find me in app/views/text_with_voices/create.html.haml

app/views/text_with_voices/edit.html.haml
%h1 TextWithVoices#edit
%p Find me in app/views/text_with_voices/edit.html.haml

app/views/text_with_voices/new.html.haml
.row-fluid
	.well.span8.offset2
		%h1 Cadastro de texto com voz:
		= simple_form_for @text_with_voice do |f|
			.span5.offset1
				%h3 Informações sobre o conteúdo:
				= f.input :title, label: "Título:"
				= f.input :author, label: "Autor:"
				= f.input :category, label: "Categoria:", placeholder: "romance, aventura..."
				= f.input :language, label: "Idioma", collection: LANGUAGES
			.span5
				%h3 Arquivos:
				= f.label :text_path, "Selecione um arquivo de texto:"
				= f.filepicker_field :text_path, onchange: 'fileUploaded("text_format")', class: "btn"
				= hidden_field_tag :text_format
				= f.label :voice_path, "Selecione um arquivo de audio:"
				= f.filepicker_field :voice_path, onchange: 'fileUploaded("voice_format")', mimetypes: 'audio/*', class: "btn"
				= hidden_field_tag :voice_format
				%br
				= f.button :submit, "Cadastrar", class: "btn btn-primary"

= javascript_include_tag "filepicker_upload"

app/views/text_with_voices/show.html.haml
%h1 TextWithVoices#show
%p Find me in app/views/text_with_voices/show.html.haml

app/views/text_with_voices/update.html.haml
%h1 TextWithVoices#update
%p Find me in app/views/text_with_voices/update.html.haml

app/views/texts/create.html.haml
%h1 Texts#create
%p Find me in app/views/texts/create.html.haml

app/views/texts/edit.html.haml
%h1 Texts#edit
%p Find me in app/views/texts/edit.html.haml

app/views/texts/new.html.haml
.row-fluid
	.well.span8.offset2
		%h1 Cadastro de texto:
		= simple_form_for @text do |f|
			.span5.offset1
				%h3 Informações sobre o conteúdo:
				= f.input :title, label: "Título:"
				= f.input :author, label: "Autor:"
				= f.input :category, label: "Categoria:", placeholder: "romance, aventura..."
				= f.input :language, label: "Idioma", collection: LANGUAGES
			.span5
				%h3 Arquivo:
				= f.label :file_path, "Selecione um arquivo de texto:"
				= f.filepicker_field :file_path, onchange: 'fileUploaded("text_format")', class: "btn"
				= hidden_field_tag :text_format
				%br
				= f.button :submit, "Cadastrar", class: "btn btn-primary"

= javascript_include_tag "filepicker_upload"

app/views/texts/show.html.haml
%h1 Texts#show
%p Find me in app/views/texts/show.html.haml

app/views/texts/update.html.haml
%h1 Texts#update
%p Find me in app/views/texts/update.html.haml

app/views/uploaded_files/index.html.haml
.row-fluid
	- if @all.length > 0
		.span8.offset2
			- @all.each do |file|
				.row-fluid
					.well.span8.offset2
						%p 
							= "#{file.title} - "
							= link_to "Mais detalhes", uploaded_file_path(file.uploaded_file)
							= " - "
							= link_to "Download", file.file_path
		.span2
			= form_tag uploaded_files_path, method: :get do
				= hidden_field_tag "search", params[:search]
				= select_tag "Filtros", options_for_select([ "Todos", "Palavra", "Texto com Voz", "Texto apenas" ], "Todos")
				= submit_tag "Filtrar"
	- else
		.span8.offset2
			%h2 Nenhuma ocorrência foi encontrada

app/views/uploaded_files/new.html.haml
.row-fluid
	.well.span12
		%h1 Selecione abaixo o tipo de arquivo que deseja fazer upload:

.row-fluid
	.span12#file-types
		.well.span4
			%h1 Palavra
			%p O arquivo de som deverá corresponder a exatamente uma palavra
			%p Utilidades:
			%ul
				%li Treinar sistemas de reconhecimento de voz
				%li Criar uma base de palavras para um sistema
			= link_to "Fazer Upload", new_audio_word_path, class: "btn btn-primary"
		.well.span4
			%h1 Texto com Voz
			%p São 2 arquivos. Um de texto e um de audio contendo o texto sendo lido.
			%p Utilidades:
			%ul
				%li Audiobooks
				%li Testar sistemas de reconhecimento de voz
			= link_to "Fazer Upload", new_text_with_voice_path, class: "btn btn-primary"
		.well.span4
			%h1 Texto apenas
			%p Neste caso você deve enviar apenas um arquivo de texto
			%p Utilidades:
			%ul
				%li Testar sistemas de reconhecimento de voz
				%li Testar sistemas de reprodução de voz
			= link_to "Fazer Upload", new_text_path, class: "btn btn-primary"

app/views/uploaded_files/show.html.haml
.well
	- @me.owner_file.attributes.each do |k, v|
		- break if v.blank?
		.row-fluid
			.span6.offset3
				%p= "#{k} - #{v}"
	.row-fluid
		.span6.offset3
			%p 
				= "URL do arquivo - "
				= link_to @me.url, @me.url

app/views/users/shared/_links.haml
- if controller_name != 'sessions'
  = link_to "Sign in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    %br/